version: "3.9"

services: 
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=dariush
        ports:
            - "5432:5432"
    api:
        build: 
            context: . 
            dockerfile: Dockerfile
        ports: 
            - "8000:8001" # left = host
        volumes: 
            - .:/code
        command: python manage.py runserver 0.0.0.0:8001
        depends_on:
            - db
    consumer:
        build: 
            context: .
            dockerfile: Dockerfile
        restart: always
        command: "python consumer.py"
        depends_on: 
            - db
            - api
            - rabbitmq
    producer:
        build: 
            context: .
            dockerfile: Dockerfile
        restart: always
        command: "python producer.py"
        depends_on: 
            - db
            - api
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3.8-management
        hostname: rabbitmq
        restart: always
        volumes:
            - ./data/rabbitmq:/var/lib/rabbitmq
        ports: 
            - "15672:15672"
            - "5672:5672"
        depends_on: 
            - db
            - api