# Generated by Django 3.1.5 on 2021-07-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolISIN', models.CharField(max_length=250)),
                ('variation', models.CharField(max_length=250)),
                ('top', models.CharField(max_length=250)),
                ('bottom', models.CharField(max_length=250)),
            ],
        ),
    ]
