# Generated by Django 3.2.5 on 2021-07-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_O_API_App', '0003_rename_symbolisin_indexes_symbolisin'),
    ]

    operations = [
        migrations.CreateModel(
            name='trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_symbol', models.CharField(max_length=20)),
                ('oper', models.IntegerField(max_length=1)),
                ('desired_price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
