# Generated by Django 3.2.5 on 2021-07-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_O_API_App', '0004_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='desired_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='oper',
            field=models.IntegerField(),
        ),
    ]
